const BT_ISSUERS = [
    "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7"
];

const HORIZON_INST = "https://horizon.stellar.org";
const MAX_SEARCH = "limit=200";

const STREET_NAME_ACCOUNTS = [
    "GAQKSRI4E5643UUUMJT4RWCZVLY25TBNZXDME4WLRIF5IPOLTLV7N4N6" // Cede & Co.
];

module.exports = { BT_ISSUERS, HORIZON_INST, MAX_SEARCH, STREET_NAME_ACCOUNTS };