const BT_ISSUERS = [
    "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7"
];

const HORIZON_INST = "https://horizon.stellar.org";
const MAX_SEARCH = "limit=200";

module.exports = { BT_ISSUERS, HORIZON_INST, MAX_SEARCH };